name: Comment on stale discussions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@2654679fe7f7c29875c669398a8ec0791b8a64a1

      - name: Bundle install
        run: bundle install

      - name: Comment on discussions
        run: .github/actions/comment
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
